[server]
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"

[global]
developmentMode = false